### ISSUE TITLE
Uknown Message status or message from unknow Inverter

### ISSUE THREAD

**Issue by ringlord** [mark0100/omniklogger#1]
I have set this up for my Omnik and the logging to pvoutput works.
But the logging shows this error each time :
```
2022-05-31 15:04:03,557 ERROR Unknown Message Status or message from unknown Inverter serial received
2022-05-31 15:04:03,558 ERROR
byte  ASC   HEX   CHR
---------------------
   0  104   0x68  h
   1   39   0x27  '
   2   81   0x51  Q
   3  177   0xb1  ±
   4  185   0xb9  ¹
   5    5   0x5
   6    8   0x8
   7   30   0x1e
   8  185   0xb9  ¹
   9    5   0x5
  10    8   0x8
  11   30   0x1e
  12  128   0x80  �
  13    1   0x1
  14   72   0x48  H
  15   52   0x34  4
  16   46   0x2e  .
  17   48   0x30  0
  18   49   0x31  1
  19   46   0x2e  .
  20   52   0x34  4
  21   52   0x34  4
  22   89   0x59  Y
  23   52   0x34  4
  24   46   0x2e  .
  25   48   0x30  0
  26   46   0x2e  .
  27   48   0x30  0
  28   49   0x31  1
  29   87   0x57  W
  30   49   0x31  1
  31   46   0x2e  .
  32   48   0x30  0
  33   46   0x2e  .
  34   49   0x31  1
  35   56   0x38  8
  36   40   0x28  (
  37   50   0x32  2
  38   48   0x30  0
  39   49   0x31  1
  40   52   0x34  4
  41   45   0x2d  -
  42   48   0x30  0
  43   57   0x39  9
  44   45   0x2d  -
  45   50   0x32  2
  46   48   0x30  0
  47   49   0x31  1
  48   41   0x29  )
  49    0   0x0
  50    0   0x0
  51  120   0x78  x
  52   22   0x16
```

**Comment by mark0100** [comment]
Please provide some debug logging:
Change the filehandler logging level in logging.ini to DEBUG and restart omniklogger. Let it run for 10 minutes or so and post your logfile here.
Note: the logfile with debug logging possibly contains your PVOutput API key in the message to PVOutput. Mask your API key in the logging before posting here!

**Comment by ringlord** [comment]
```
2022-05-31 15:13:20,350 INFO Starting omniklogger
2022-05-31 15:13:20,350 INFO Importing output plugin: PVoutputOutput
2022-05-31 15:13:20,386 INFO Omniklogger up and listening on 192.x.x.x on port xxxx with loglevel: DEBUG
2022-05-31 15:13:20,386 INFO We are listening for UDP messages from an Inverter with serial: b'NLDN************'
2022-05-31 15:14:57,638 ERROR Unknown Message Status or message from unknown Inverter serial received
2022-05-31 15:14:57,638 ERROR
byte  ASC   HEX   CHR
---------------------
   0  104   0x68  h
   1   39   0x27  '
   2   81   0x51  Q
   3  177   0xb1  ±
   4  185   0xb9  ¹
   5    5   0x5
   6    8   0x8
   7   30   0x1e
   8  185   0xb9  ¹
   9    5   0x5
  10    8   0x8
  11   30   0x1e
  12  128   0x80  �
  13    1   0x1
  14   72   0x48  H
  15   52   0x34  4
  16   46   0x2e  .
  17   48   0x30  0
  18   49   0x31  1
  19   46   0x2e  .
  20   52   0x34  4
  21   52   0x34  4
  22   89   0x59  Y
  23   52   0x34  4
  24   46   0x2e  .
  25   48   0x30  0
  26   46   0x2e  .
  27   48   0x30  0
  28   49   0x31  1
  29   87   0x57  W
  30   49   0x31  1
  31   46   0x2e  .
  32   48   0x30  0
  33   46   0x2e  .
  34   49   0x31  1
  35   56   0x38  8
  36   40   0x28  (
  37   50   0x32  2
  38   48   0x30  0
  39   49   0x31  1
  40   52   0x34  4
  41   45   0x2d  -
  42   48   0x30  0
  43   57   0x39  9
  44   45   0x2d  -
  45   50   0x32  2
  46   48   0x30  0
  47   49   0x31  1
  48   41   0x29  )
  49    0   0x0
  50    0   0x0
  51  120   0x78  x
  52   22   0x16

```

**Comment by mark0100** [comment]
Hi Ringlord,

I don't see any DEBUG lines in your logging?!

Have you set the level variable to DEBUG in the filehandler section of you logging.ini?
Example:
************************************************************************************************
[handler_filehandler]
class=FileHandler
#level=INFO
level=DEBUG                   <<<<================== set this variable to DEBUG 
formatter=formatter
args=("/home/mark/omniklogger/omniklogger.log", "a")
*************************************************************************************************
And did you restart omniklogger after saving the changes?

If the level is set to DEBUG you should see a lot more log lines with level DEBUG in your logfile.

PS: to avoid that your PVOutput key will be shown in the logfile i think you can also temporarily remove PVOutput as a plugable output in config.ini. 
I.e. just set the variable enabled_plugins = ConsoleOutput in your config.ini and restart omniklogger.

**Comment by ringlord** [comment]
```
2022-05-31 16:28:41,213 INFO Starting omniklogger
2022-05-31 16:28:41,213 INFO Importing output plugin: ConsoleOutput
2022-05-31 16:28:41,214 INFO Omniklogger up and listening on 192.168.1.253 on port 5454 with loglevel: DEBUG
2022-05-31 16:28:41,214 INFO We are listening for UDP messages from an Inverter with serial: b'NLDN302014CF4095'
2022-05-31 16:31:15,465 DEBUG Message from ('192.168.1.249', 5454) received
2022-05-31 16:31:15,465 DEBUG msg.status: b'\x81\x02\x01NLDN302014CF4' msg.aknowledge: b'\x81\x02\x01NLDN302014CF' msg.id: b'NLDN302014CF4095' serial: b'NLDN302014CF4095'
2022-05-31 16:31:15,465 DEBUG Received data from Inverter with serial: b'NLDN302014CF4095'
2022-05-31 16:31:15,465 DEBUG Running plugin: type
2022-05-31 16:31:15,794 DEBUG Message from ('192.168.1.249', 5454) received
2022-05-31 16:31:15,795 DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'
2022-05-31 16:31:15,795 ERROR Unknown Message Status or message from unknown Inverter serial received
2022-05-31 16:31:15,795 ERROR
byte  ASC   HEX   CHR
---------------------
   0  104   0x68  h
   1   39   0x27  '
   2   81   0x51  Q
   3  177   0xb1  ±
   4  185   0xb9  ¹
   5    5   0x5
   6    8   0x8
   7   30   0x1e
   8  185   0xb9  ¹
   9    5   0x5
  10    8   0x8
  11   30   0x1e
  12  128   0x80  �
  13    1   0x1
  14   72   0x48  H
  15   52   0x34  4
  16   46   0x2e  .
  17   48   0x30  0
  18   49   0x31  1
  19   46   0x2e  .
  20   52   0x34  4
  21   52   0x34  4
  22   89   0x59  Y
  23   52   0x34  4
  24   46   0x2e  .
  25   48   0x30  0
  26   46   0x2e  .
  27   48   0x30  0
  28   49   0x31  1
  29   87   0x57  W
  30   49   0x31  1
  31   46   0x2e  .
  32   48   0x30  0
  33   46   0x2e  .
  34   49   0x31  1
  35   56   0x38  8
  36   40   0x28  (
  37   50   0x32  2
  38   48   0x30  0
  39   49   0x31  1
  40   52   0x34  4
  41   45   0x2d  -
  42   48   0x30  0
  43   57   0x39  9
  44   45   0x2d  -
  45   50   0x32  2
  46   48   0x30  0
  47   49   0x31  1
  48   41   0x29  )
  49    0   0x0
  50    0   0x0
  51  120   0x78  x
  52   22   0x16

```

**Comment by ringlord** [comment]
I also have 2 'channels'   PV1 and PV2, but the logger only logs the voltage of PV1.


ID: b'NLDN302014CF4095'
E Today: 13.31   Total: 23684.7
H Total: 29046   Temp:  37.1
PV1   V: 203.7   I:  2.5
PV2   V: 159.8   I:  2.2
PV3   V:    -1   I:   -1
L1    P:   768   V: 238.7   I:  3.2   F: 50.03
L2    P:    -1   V:    -1   I:   -1   F:    -1
L3    P:    -1   V:    -1   I:   -1   F:    -1

**Comment by mark0100** [comment]
Thanks ringlord. 

I think it's an aknowledge message that sets the error. I have a look at it and compare to my installation.
When i know more i get back to you.

Regards,

Mark

**Comment by mark0100** [comment]
***********************************************************************************************
I also have 2 'channels' PV1 and PV2, but the logger only logs the voltage of PV1.

ID: b'NLDN302014CF4095'
E Today: 13.31 Total: 23684.7
H Total: 29046 Temp: 37.1
PV1 V: 203.7 I: 2.5
PV2 V: 159.8 I: 2.2
PV3 V: -1 I: -1
L1 P: 768 V: 238.7 I: 3.2 F: 50.03
L2 P: -1 V: -1 I: -1 F: -1
L3 P: -1 V: -1 I: -1 F: -1
***********************************************************************************************
PV1 and PV2 are set with their voltage and current.

Or maybe you mean in PVOutput? PVOutput only shows the E-today (in Watts from all strings added together) and the voltage measured by your inverter of the AC (output) connection. And if you set the use_temperature in config.ini the temperature of the inverter is also send to PVOutput.

**Comment by ringlord** [comment]
I have created a separate issue for this to keep the 2 apart.

**Comment by mark0100** [comment]
Hi ringlord,

I tried to reproduce your problem here but i can't. It looks like the second message that raises the error in your log is supposed to be an aknowledge message ('DATA SEND IS OK') but somehow it looks completely different that what i get from my inverter.

If i look in my logfile i get the following pairs of messages:
************************************************************************************************************
2022-05-31 19:36:43,220 DEBUG Message from ('192.168.2.1', 20001) received
2022-05-31 19:36:43,221 DEBUG msg.status: b'\x81\x02\x01NLDN3020138T1' msg.aknowledge: b'\x81\x02\x01NLDN3020138T' msg.id: b'NLDN3020138T1242' serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,221 DEBUG Received data from Inverter with serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,221 DEBUG Running plugin: type
2022-05-31 19:36:43,229 DEBUG Message from ('192.168.2.1', 20001) received
2022-05-31 19:36:43,229 DEBUG msg.status: b'DATA SEND IS OK\r' msg.aknowledge: b'DATA SEND IS OK' msg.id: b'A SEND IS OK\r\nr\x16' serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,230 DEBUG Aknowledgement message received from Inverter: DATA SEND IS OK
************************************************************************************************************
First i get a data message and then an aknowledge message where the msg.status field and the msg.aknowledge field contain 'DATA SEND IS OK'.

What kind of Omnik inverter do you have? Can you upload your device information from the inverter configuration page?

**Comment by ringlord** [comment]
Op di, mei 31, 2022 om 19:54 schreef ***@***.***>:   


Hi ringlord,

I tried to reproduce your problem here but i can't. It looks like the second message that raises the error in your log is supposed to be an aknowledge message ('DATA SEND IS OK') but somehow it looks completely different that what i get from my inverter.

If i look in my logfile i get the following pairs of messages:

2022-05-31 19:36:43,220 DEBUG Message from ('192.168.2.1', 20001) received
2022-05-31 19:36:43,221 DEBUG msg.status: b'\x81\x02\x01NLDN3020138T1' msg.aknowledge: b'\x81\x02\x01NLDN3020138T' msg.id: b'NLDN3020138T1242' serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,221 DEBUG Received data from Inverter with serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,221 DEBUG Running plugin: type
2022-05-31 19:36:43,229 DEBUG Message from ('192.168.2.1', 20001) received
2022-05-31 19:36:43,229 DEBUG msg.status: b'DATA SEND IS OK\r' msg.aknowledge: b'DATA SEND IS OK' msg.id: b'A SEND IS OK\r\nr\x16' serial: b'NLDN3020138T1242'
2022-05-31 19:36:43,230 DEBUG Aknowledgement message received from Inverter: DATA SEND IS OK

First i get a data message and then an aknowledge message where the msg.status field and the msg.aknowledge field contain 'DATA SEND IS OK'.

What kind of Omnik inverter do you have? Can you upload your device information from the inverter configuration page?

**Comment by ringlord** [comment]
Type   Omnik
Number 1
Inverter serial number   NLDN302014CF4095
Firmware version (main)  AU1-V1.0-0113-4
Firmware version (slave)  V2.0-0028
Inverter model   omnik3000tl
Rated power  3000 W

In the second message that the inverter sends 
I recognize part of the Firmware version H4.01.44Y4.0.01W1.0.18(2014-09-201)  of the logger.

DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'

**Comment by mark0100** [comment]
Hi ringlord,

We have the same device but the firmware versions differ.
My firmware versions are:
**************************************************
Firmware version (main) NL1-V1.0-0061-4
Firmware version (slave) V2.0-0024
Firmware version logger H4.01.36Y1.0.05W1.0.04
**************************************************
It looks like your aknowledge/confirmation message is very different than mine and i don't see any status fields in your message we could use. The message looks gibberish to me except that it contains the firmware version and a production date?? of your logger as you pointed out.

We are not doing anything in the code at the moment with the confirmation messages, except counting them to show some stats.
So for now we could just treat them as an unknown message and not as an error i guess. That would solve the error messages in the logfile you are experiencing.

I will update the code accordingly.

In the mean time as a temporary fix to get rid of the error messages you could change the logging level from logger.error to logger.debug in omniklogger.py in the else branch and restart omniklogger:
***********************************************************************
...
    else:
        msgErrorCount = msgErrorCount + 1
        logger.error('Unknown Message Status or message from unknown Inverter serial received')
        logger.error(msg.dump()) 
...
************************************************************************

**Comment by ringlord** [comment]
OK that fixes it for me.
Thanks for the solution.
I will now use this logger for a longer time to see whether it is more robust then my previous setup.

**Comment by mark0100** [comment]
Hi ringlord,

I updated the sources with the fix.

Please install the latest version and test with log level DEBUG.
You should see a log entry on DEBUG level for every unknown message you get from the logger. The log line should show your logger firmware version. The errors should be gone.

Kind regards,

Mark

**Comment by ringlord** [comment]
I don't think this is as expected ?
PS I also noticed that the logging is now each 5 minutes and yesterday it was every 10 minutes, how could that be changed?
```
2022-06-01 16:22:35,469 INFO Starting omniklogger
2022-06-01 16:22:35,469 INFO Importing output plugin: PVoutputOutput
2022-06-01 16:22:35,501 INFO Waiting 10 seconds before startup...
2022-06-01 16:22:45,511 INFO Omniklogger up and listening on 192.168.1.253 on port 5454 with loglevel: DEBUG
2022-06-01 16:22:45,511 INFO We are listening for UDP messages from an Inverter with serial: b'NLDN302014CF4095'
2022-06-01 16:27:54,418 DEBUG Message from ('192.168.1.249', 5454) received
2022-06-01 16:27:54,418 DEBUG msg.status: b'\x81\x02\x01NLDN302014CF4' msg.aknowledge: b'\x81\x02\x01NLDN302014CF' msg.id: b'NLDN302014CF4095' serial: b'NLDN302014CF4095'
2022-06-01 16:27:54,418 DEBUG Received data from Inverter with serial: b'NLDN302014CF4095'
2022-06-01 16:27:54,418 DEBUG Running plugin: type
2022-06-01 16:27:54,418 DEBUG PVOutputoutput: Uploading to PVoutput
2022-06-01 16:27:54,420 DEBUG PVoutputOutput request: http://pvoutput.org/service/r2/addstatus.jsp?
2022-06-01 16:27:54,842 DEBUG PVoutputOutput: response from PVOutput site: b'OK 200: Added Status'
2022-06-01 16:27:54,842 DEBUG Message from ('192.168.1.249', 5454) received
2022-06-01 16:27:54,843 DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'
2022-06-01 16:27:54,843 ERROR Unknown Message Status or message from unknown Inverter serial received
2022-06-01 16:27:54,843 ERROR
byte  ASC   HEX   CHR
---------------------
   0  104   0x68  h
   1   39   0x27  '
   2   81   0x51  Q
   3  177   0xb1  ±
   4  185   0xb9  ¹
   5    5   0x5
   6    8   0x8
   7   30   0x1e
   8  185   0xb9  ¹
   9    5   0x5
  10    8   0x8
  11   30   0x1e
  12  128   0x80  �
  13    1   0x1
  14   72   0x48  H
  15   52   0x34  4
  16   46   0x2e  .
  17   48   0x30  0
  18   49   0x31  1
  19   46   0x2e  .
  20   52   0x34  4
  21   52   0x34  4
  22   89   0x59  Y
  23   52   0x34  4
  24   46   0x2e  .
  25   48   0x30  0
  26   46   0x2e  .
  27   48   0x30  0
  28   49   0x31  1
  29   87   0x57  W
  30   49   0x31  1
  31   46   0x2e  .
  32   48   0x30  0
  33   46   0x2e  .
  34   49   0x31  1
  35   56   0x38  8
  36   40   0x28  (
  37   50   0x32  2
  38   48   0x30  0
  39   49   0x31  1
  40   52   0x34  4
  41   45   0x2d  -
  42   48   0x30  0
  43   57   0x39  9
  44   45   0x2d  -
  45   50   0x32  2
  46   48   0x30  0
  47   49   0x31  1
  48   41   0x29  )
  49    0   0x0
  50    0   0x0
  51  120   0x78  x
  52   22   0x16

2022-06-01 16:33:12,535 DEBUG Message from ('192.168.1.249', 5454) received
2022-06-01 16:33:12,535 DEBUG msg.status: b'\x81\x02\x01NLDN302014CF4' msg.aknowledge: b'\x81\x02\x01NLDN302014CF' msg.id: b'NLDN302014CF4095' serial: b'NLDN302014CF4095'
2022-06-01 16:33:12,535 DEBUG Received data from Inverter with serial: b'NLDN302014CF4095'
2022-06-01 16:33:12,535 DEBUG Running plugin: type
2022-06-01 16:33:12,535 DEBUG PVOutputoutput: Uploading to PVoutput
2022-06-01 16:33:12,536 DEBUG PVoutputOutput request: http://pvoutput.org/service/r2/addstatus.jsp?
2022-06-01 16:33:12,908 DEBUG PVoutputOutput: response from PVOutput site: b'OK 200: Added Status'
2022-06-01 16:33:12,909 DEBUG Message from ('192.168.1.249', 5454) received
2022-06-01 16:33:12,909 DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'
2022-06-01 16:33:12,909 ERROR Unknown Message Status or message from unknown Inverter serial received
2022-06-01 16:33:12,909 ERROR
byte  ASC   HEX   CHR

```

**Comment by ringlord** [comment]
I see here https://github.com/XtheOne/Inverter-Data-Logger that the protocol used is related to the serial number of the logger.
My serial is 503842233
In https://github.com/XtheOne/Inverter-Data-Logger/blob/master/InverterMsg.py  we also see  a '#V4 table'  
Is it possible that my logger is sending out a bigger datastream on the first go?

**Comment by mark0100** [comment]
Hi ringlord,

I think i made a mistake in the length of the message. The problem is that i can't really test it here myself and are coding in the dark without the actual message. So please bare with me.

I updated the source and also added some debug logging to show the length of messages.
Please update with the latest version and run with debug logging again. Just use the ConsoleOutput as plugable output when testing to simplify logging results.

Regarding the message interval:
My inverter sends about every 5 minutes a data packet to omniklogger. I'm not sure why you had a data packet every 10 minutes earlier.

My logger device serial number starts with 605.
I'm not sure but the other packages you are referring to use TCP and not UDP like omniklogger does. I think the message structure is not the same for these different protocols.

**Comment by ringlord** [comment]
Consoleoutput did not seem to log anything I probably did not set some value correctly
```
2022-06-02 08:14:48,785 INFO Starting omniklogger
2022-06-02 08:14:48,786 INFO Importing output plugin: PVoutputOutput
2022-06-02 08:14:48,817 INFO Waiting 10 seconds before startup...
2022-06-02 08:14:58,827 INFO Omniklogger up and listening on 192.168.1.253 on port 5454 with loglevel: DEBUG
2022-06-02 08:14:58,827 INFO We are listening for UDP messages from an Inverter with serial: b'NLDN302014CF4095'
2022-06-02 08:17:47,403 DEBUG Message from ('192.168.1.249', 5454) received. Message length: 143
2022-06-02 08:17:47,403 DEBUG msg.status: b'\x81\x02\x01NLDN302014CF4' msg.aknowledge: b'\x81\x02\x01NLDN302014CF' msg.id: b'NLDN302014CF4095' serial: b'NLDN302014CF4095'
2022-06-02 08:17:47,403 DEBUG Received data from Inverter with serial: b'NLDN302014CF4095'
2022-06-02 08:17:47,404 DEBUG Running plugin: type
2022-06-02 08:17:47,404 DEBUG PVOutputoutput: Uploading to PVoutput
2022-06-02 08:17:47,405 DEBUG PVoutputOutput request: http://pvoutput.org/service/r2/addstatus.jsp?
2022-06-02 08:17:47,716 DEBUG PVoutputOutput: response from PVOutput site: b'OK 200: Added Status'
2022-06-02 08:17:47,733 DEBUG Message from ('192.168.1.249', 5454) received. Message length: 53
2022-06-02 08:17:47,733 DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'
```

This I got on the screen :

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "omniklogger.py", line 116, in <module>
    logger.debug('Unknown logger message received from logger with firmware version: {0}', format(msg.firmware_logger))
Message: 'Unknown logger message received from logger with firmware version: {0}'
Arguments: ("b'H4.01.44Y4.0.01W1.0.18'",)
^CTraceback (most recent call last):
  File "omniklogger.py", line 93, in <module>
    bytesAddressPair = UDPServerSocket.recvfrom(1024)
KeyboardInterrupt

```

**Comment by mark0100** [comment]
Hi ringlord,

You did everything fine. The program had an error. My mistake but i think i fixed it now.
We are getting there...

Please install the latest omniklogger.py and try again.

**Comment by ringlord** [comment]
New testresult
```
2022-06-02 09:31:21,454 INFO Starting omniklogger
2022-06-02 09:31:21,454 INFO Importing output plugin: PVoutputOutput
2022-06-02 09:31:21,485 INFO Waiting 10 seconds before startup...
2022-06-02 09:31:31,493 INFO Omniklogger up and listening on 192.168.1.253 on port 5454 with loglevel: DEBUG
2022-06-02 09:31:31,494 INFO We are listening for UDP messages from an Inverter with serial: b'NLDN302014CF4095'
2022-06-02 09:33:56,655 DEBUG Message from ('192.168.1.249', 5454) received. Message length: 143
2022-06-02 09:33:56,655 DEBUG msg.status: b'\x81\x02\x01NLDN302014CF4' msg.aknowledge: b'\x81\x02\x01NLDN302014CF' msg.id: b'NLDN302014CF4095' serial: b'NLDN302014CF4095'
2022-06-02 09:33:56,655 DEBUG Received data from Inverter with serial: b'NLDN302014CF4095'
2022-06-02 09:33:56,655 DEBUG Running plugin: type
2022-06-02 09:33:56,655 DEBUG PVOutputoutput: Uploading to PVoutput
2022-06-02 09:33:56,657 DEBUG PVoutputOutput request: http://pvoutput.org/service/r2/addstatus.jsp?
2022-06-02 09:33:56,939 DEBUG PVoutputOutput: response from PVOutput site: b'OK 200: Added Status'
2022-06-02 09:33:56,985 DEBUG Message from ('192.168.1.249', 5454) received. Message length: 53
2022-06-02 09:33:56,985 DEBUG msg.status: b'\x80\x01H4.01.44Y4.0.0' msg.aknowledge: b'\x80\x01H4.01.44Y4.0.' msg.id: b'4.01.44Y4.0.01W1' serial: b'NLDN302014CF4095'
2022-06-02 09:33:56,985 DEBUG Unknown logger message received from logger with firmware version: b'H4.01.44Y4.0.01W1.0.18'
```

**Comment by mark0100** [comment]
That looks great. I think we fixed it. The strange messages are now just ignored and only when the loglevel is set to DEBUG you see a single logline for every message. They will no longer cause an error.

Thank you for the testing effort ringlord.
